use_frameworks!
platform :ios, '9.0'

target 'RxUIApplicationDelegate_Example' do
  pod 'RxUIApplicationDelegate', :path => '../'

  target 'RxUIApplicationDelegate_Tests' do
    inherit! :search_paths
  end
end
